### ISSUE TITLE
Couldn't find the "public/out/secp256k1.js" file

### ISSUE THREAD

**Issue by genki** [SolarRepublic/wasm-secp256k1#2]
I have tried to build this project but that file is not found in this repo.
Could you tell me where can I find it?

**Comment by blake-regalia** [comment]
I updated the README to include [build instructions here](https://github.com/SolarRepublic/wasm-secp256k1#building-from-source). Hope this helps!

**Comment by genki** [comment]
Thank you for writing it.
But it is still failing at `bun run build` like this:

```sh
$ bun run ./src/generate.ts public/out/secp256k1.js > ./src/gen/wasm.ts
11 | if(!sr_file) {
12 |    console.error('Usage: generate.ts <WASM_JS_FILE>');
13 |    process.exit(1);
14 | }
15 | 
16 | const sx_js = readFileSync(sr_file, 'utf-8');
                  ^
ENOENT: No such file or directory
   path: "public/out/secp256k1.js"
 syscall: "open"
   errno: -2
```

**Comment by genki** [comment]
Ah, I see. I had used the remote docker server that can't refer the local `public/` dir.
